# docker-compose file that builds new images
services:
  reelminder_postgres:
    image: postgres
    container_name: reelminder_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/reelminder
    networks:
      - internalnet

  reelminder_frontend:
    container_name: reelminder_frontend
    build:
      context: ./frontend/reelminder
    image: reelminder_frontend:v1
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet

  reelminder_backend:
    container_name: reelminder_backend
    env_file:
      - .env
    build:
      context: ./backend/reelminder
    image: reelminder_backend:v1
    ports:
      - 8000:8000
    expose:
      - 8000
    networks:
      - internalnet

volumes:
  postgres_data: {}

networks:
  internalnet:
    driver: bridge
