services:
  reelminder_frontend:
    container_name: reelminder_frontend
    build:
      context: ./frontend/reelminder
    image: reelminder_frontend:v1
    ports: 
      - 80:80
    expose:
      - 80
    networks:
      - internalnet
  
  reelminder_backend:
    container_name: reelminder_backend
    env_file:
      - ./backend/reelminder/.env
    build: 
      context: ./backend/reelminder
    image: reelminder_backend:v1
    ports:
      - 8000:8000
    expose:
      - 8000
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge