# docker-compose file using images from the remote registry
services:
  reelminder_frontend:
    container_name: reelminder_frontend
    image: ghcr.io/marataj/reelminder-frontend:v1
    ports: 
      - 80:80
    expose:
      - 80
    networks:
      - internalnet
  
  reelminder_backend:
    container_name: reelminder_backend
    env_file:
      - ./backend/reelminder/.env
    image: ghcr.io/marataj/reelminder-backend:v1
    ports:
      - 8000:8000
    expose:
      - 8000
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
