# Generated by Django 5.0.1 on 2024-01-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("color", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("movie_id", models.CharField(max_length=50)),
                ("creation_date", models.DateTimeField()),
                ("is_public", models.BooleanField()),
                ("author", models.CharField(max_length=50)),
                ("progress_sec", models.IntegerField()),
                ("labels", models.ManyToManyField(blank=True, to="course.label")),
            ],
        ),
    ]
