POST http://127.0.0.1:8000/auth/register/
Content-Type: application/json

{
    "username": "mat",
    "email": "mat@mat.pl",
    "password": "mateusz123",
    "password2": "mateusz123"
}

###

POST http://127.0.0.1:8000/auth/token/
Content-Type: application/json

{
    "username": "mat",
    "password": "mateusz123"
}

###

GET http://127.0.0.1:8000/auth/profile/
Content-Type: application/json
Authorization: Bearer ......

{
    
}

###

PUT http://127.0.0.1:8000/auth/profile/update/
Content-Type: application/json
Authorization: Bearer .......

{
    "password": "",
    "confirmation_password": ""
}

###

POST http://127.0.0.1:8000/auth/token/refresh/
Content-Type: application/json

{
    "refresh": "......."
}